services:
  ros2_sim:
    image: ros2_agrorobot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrorobot_sim
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, display, graphics, utility]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/ros2_ws/src:ro
      - ./ros2_ws_build:/ros2_ws/build
      - ./ros2_ws_install:/ros2_ws/install
      - ./ros2_ws_log:/ros2_ws/log
    devices:
      - /dev/dri
      - /dev/input
    privileged: false
    stdin_open: true
    tty: true
    command: >
      bash -c "cd /ros2_ws &&
               colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release &&
               source install/setup.bash &&
               ros2 launch my_robot test.launch.py"
