# controller_manager:
#   ros__parameters:
#     update_rate: 100 # Hz

#     forward_velocity_controller:
#       type: forward_command_controller/ForwardCommandController

#     forward_position_controller:
#       type: forward_command_controller/ForwardCommandController

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# forward_velocity_controller:
#   ros__parameters:
#     joints:
#       - joint_l_w
#       - joint_r_w
#     interface_name: velocity
#     command_interfaces:
#       - velocity
#     state_interfaces:
#       - position
#       - velocity

# forward_position_controller:
#   ros__parameters:
#     joints:
#       - joint_f_l
#       - joint_f_r
#     interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
     






























controller_manager:
  ros__parameters:
    update_rate: 30  # Гц (совместимо с Gazebo)
    use_sim_time: true

    # diff_cont:
    #   type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    # acker_cont:
    #   type: ackermann_steering_controller/AckermannSteeringController
    position_controller:
      type: position_controllers/JointGroupPositionController
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: base_link_to_wheeling_mech

velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints: 
        - front_right_base_to_front_right_wheel
        - front_left_base_to_front_left_wheel
        - back_right_base_to_back_right_wheel
        - back_left_base_to_back_left_wheel
    # Контроллер для задних ведущих колес (Diff Drive)
# acker_cont:
#   ros__parameters:
#     type: ackermann_steering_controller/AckermannSteeringController
#     reference_timeout: 2.0
#     open_loop: false
#     velocity_rolling_window_size: 10
#     position_feedback: false
#     rear_wheels_names: [joint_r_w, joint_l_w]
#     front_wheels_names: [joint_f_r_w, joint_f_l_w]

#     front_wheel_track: 0.5
#     rear_wheel_track: 0.5
#     front_wheels_radius: 0.1
#     rear_wheels_radius: 0.2
#     wheelbase: 3.24644
#     traction_track_width: 1.76868
#     traction_wheels_radius: 0.45


# diff_cont:
#   ros__parameters:
#     type: diff_drive_controller/DiffDriveController
  
#     left_wheel_names: ['joint_l_w']
#     right_wheel_names: ['joint_r_w']
#     wheel_separation: 0.3  # Ширина колеи (настройте под ваш робот)
#     wheel_radius: 0.03      # Радиус колес
#     publish_rate: 50.0     # Частота публикации odometry

#     odom_frame_id: odom
#     base_frame_id: base_link
#     pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#     twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

#     position_feedback: false
#     open_loop: true
#     enable_odom_tf: true

#     use_stamped_vel: true
#     cmd_vel_timeout: 0.5 # seconds
#     publish_limited_velocity: true
#     velocity_rolling_window_size: 10

#     linear.x.max_velocity: .NAN
#     linear.x.min_velocity: .NAN
#     linear.x.max_acceleration: .NAN
#     linear.x.max_deceleration: .NAN
#     linear.x.max_acceleration_reverse: .NAN
#     linear.x.max_deceleration_reverse: .NAN
#     linear.x.max_jerk: .NAN
#     linear.x.min_jerk: .NAN

#     angular.z.max_velocity: .NAN
#     angular.z.min_velocity: .NAN
#     angular.z.max_acceleration: .NAN
#     angular.z.max_deceleration: .NAN
#     angular.z.max_acceleration_reverse: .NAN
#     angular.z.max_deceleration_reverse: .NAN
#     angular.z.max_jerk: .NAN
#     angular.z.min_jerk: .NAN
    # Контроллеры для передних колес:
    # 1. Поворот элементов (рулевое управление)
    # front_steering_controller:
    #   type: position_controllers/JointGroupPositionController
    #   ros__parameters:
    #     joints: ['joint_f_r', 'joint_f_l']
    #     interface_name: 'position'
        

    # 2. Вращение передних колес (если они приводные)
    # front_wheels_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController
    #   ros__parameters:
    #     joints: ['joint_f_r_w', 'joint_f_l_w']
    #     interface_name: 'velocity'