controller_manager:
  ros__parameters:
    update_rate: 1000
   

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_controller:
      type: ackermann_steering_controller/AckermannSteeringController
      ros__parameters:
        front_wheel_names: ["joint_f_l", "joint_f_r"]
        rear_wheel_names: ["joint_l_w", "joint_r_w"]
        wheelbase: 0.5
        wheel_radius: 0.1