ekf_node:
    ros__parameters:
        frequency: 50.0  # Увеличиваем частоту обработки
        
        two_d_mode: true  # Работаем в 2D плоскости
        publish_acceleration: false
        publish_tf: false
        
        # Системы координат
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: fito_world  # Используем odom как мировую СК

        # Настройки одометрии
        odom0: /odom
        odom0_config: [true,  true,  false,   # X, Y, Z позиция
                      false, false, false,   # Roll, Pitch, Yaw
                      true, true, true,   # X, Y, Z velocity
                      true, true, true,    # Roll, Pitch, Yaw velocity
                      true, true, true]   # Linear acceleration
        
        # Настройки IMU
        imu0: /imu
        imu0_config: [true,  true,  false,   # X, Y, Z позиция
                      false, false, false,   # Roll, Pitch, Yaw
                      true, true, true,   # X, Y, Z velocity
                      true, true, true,    # Roll, Pitch, Yaw velocity
                      true, true, true]   # Не используем линейные ускорения

        # Параметры фильтрации
