controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController
    wheel_joints_controller:
      type: velocity_controllers/JointGroupVelocityController
    steering_controller:
      type: position_controllers/JointPositionController
ackermann_steering_controller:
  ros__parameters:
    type: ackermann_steering_controller/AckermannSteeringController

    # Wheel parameters
    front_wheels_names: ["front_left_wheel", "front_right_wheel"]
    rear_wheels_names: ["back_left_wheel", "back_right_wheel"]
    steering_joints_names: ["base_link_to_wheeling_mech"]
    
    # Robot geometry
    wheelbase: 1.863  # Distance between front and rear axles (2.11 - (-1.051) + 0.585)
    track_width: 1.24  # Distance between wheels (0.62*2)
    wheel_radius: 0.37  # Wheel radius in meters

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s²
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.57  # rad/s (~90 deg/s)
        has_acceleration_limits: true
        max_acceleration: 0.5  # rad/s²

      # PID gains for velocity control
wheel_joints_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - front_left_wheel
      - front_right_wheel
      - back_left_wheel
      - back_right_wheel
    gains:
      front_left_wheel: {p: 0.5, i: 0.1, d: 0.0}
      front_right_wheel: {p: 0.5, i: 0.1, d: 0.0}
      back_left_wheel: {p: 0.5, i: 0.1, d: 0.0}
      back_right_wheel: {p: 0.5, i: 0.1, d: 0.0}

  # PID gains for steering control
steering_controller:
  ros__parameters:
    type: position_controllers/JointPositionController
    joint: base_link_to_wheeling_mech
    gains: {p: 10.0, i: 0.1, d: 0.5}

  # Odometry settings
  # publish_rate: 50.0  # Hz
  # open_loop: false
  # enable_odom_tf: true
  # odom_frame_id: odom
  # base_frame_id: base_link
  # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

  # # Command timeout
  # cmd_timeout: 0.5  # seconds