controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ackermann_drive_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_base_to_front_left_wheel", "back_left_base_to_back_left_wheel"]
    right_wheel_names: ["front_right_base_to_front_right_wheel", "back_right_base_to_back_right_wheel"]
    steering_joints: ["base_link_to_wheeling_mech"]

    wheel_separation: 1.28       # Расстояние между левыми и правыми колесами (по Y)
    wheel_base: 1.863            # Расстояние между передней и задней осями (по X)
    wheel_radius: 0.37           # Радиус колеса

    # Параметры odometry
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint

    # Ограничения
    velocity_lim: 1.0            # м/с
    steering_angle_lim: 0.4      # рад (макс. угол поворота)

    # Коэффициенты PID для колес
    wheel:
      velocity_controllers:
        type: velocity_controllers/JointVelocityController
        gains:
          front_left_base_to_front_left_wheel: {p: 0.5, i: 0.1, d: 0.0}
          front_right_base_to_front_right_wheel: {p: 0.5, i: 0.1, d: 0.0}
          back_left_base_to_back_left_wheel: {p: 0.5, i: 0.1, d: 0.0}
          back_right_base_to_back_right_wheel: {p: 0.5, i: 0.1, d: 0.0}

    # Коэффициенты PID для рулевого механизма
    steering:
      position_controllers:
        type: position_controllers/JointPositionController
        gains:
          base_link_to_wheeling_mech: {p: 10.0, i: 0.1, d: 0.5}