controller_manager:
  ros__parameters:
    update_rate: 30  # Гц (совместимо с Gazebo)
    use_sim_time: true

    # diff_cont:
    #   type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    # acker_cont:
    #   type: ackermann_steering_controller/AckermannSteeringController
    position_controller:
      type: position_controllers/JointGroupPositionController
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: base_link_to_wheeling_mech

velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints: 
        - front_right_base_to_front_right_wheel
        - front_left_base_to_front_left_wheel
        - back_right_base_to_back_right_wheel
        - back_left_base_to_back_left_wheel
 