ekf_node:
    ros__parameters:
        frequency: 50.0  # Увеличиваем частоту обработки
        
        two_d_mode: true  # Работаем в 2D плоскости
        publish_acceleration: false
        publish_tf: true
        
        # Системы координат
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom  # Используем odom как мировую СК

        # Настройки одометрии
        odom0: /odom
        odom0_config: [true,  true,  false,   # X, Y, Z позиция
                      false, false, false,   # Roll, Pitch, Yaw
                      false, false, false,   # X, Y, Z velocity
                      false, false, true,    # Roll, Pitch, Yaw velocity
                      false, false, false]   # Linear acceleration
        
        # Настройки IMU
        imu0: /imu
        imu0_config: [false, false, false,   # Не используем позицию IMU
                      false, false, true,    # Используем только Yaw из ориентации
                      true,  true,  false,   # Используем линейные скорости X,Y
                      false, false, true,    # Используем угловую скорость Z
                      false, false, false]   # Не используем линейные ускорения

        # Параметры фильтрации
        process_noise_covariance: [0.05, 0,    0,    0,    0,    0,
                                  0,    0.05, 0,    0,    0,    0,
                                  0,    0,    0.06, 0,    0,    0,
                                  0,    0,    0,    0.03, 0,    0,
                                  0,    0,    0,    0,    0.03, 0,
                                  0,    0,    0,    0,    0,    0.01]

        initial_estimate_covariance: [0.1, 0,    0,    0,    0,    0,
                                     0,    0.1, 0,    0,    0,    0,
                                     0,    0,    0.1, 0,    0,    0,
                                     0,    0,    0,    0.1, 0,    0,
                                     0,    0,    0,    0,    0.1, 0,
                                     0,    0,    0,    0,    0,    0.1]